services:

  nats-server:
    build: ./Gateway-Service/nats
    ports:
      - 4222:4222
    restart: always

  gateway-service:
    build:
      context: ./Gateway-Service
      dockerfile: dockerfile.prod
    env_file:
      - .env
      - ./Gateway-Service/.env.compose
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./Gateway-Service:/app
      - ./Gateway-Service/package.json:/app/package.json
    restart: always

  beneficiary-service:
    build:
      context: ./Beneficiary-Service
      dockerfile: dockerfile.prod
    env_file:
      - .env
      - ./Beneficiary-Service/.env.compose
    volumes:
      - ./Beneficiary-Service:/app
      - ./Beneficiary-Service/package.json:/app/package.json
    restart: always

  global-service:
    build:
      context: ./Global-Service
      dockerfile: dockerfile.prod
    env_file:
      - .env
      - ./Global-Service/.env.compose
    volumes:
      - ./Global-Service:/app
      - ./Global-Service/package.json:/app/package.json
    restart: always

  auth-service:
    build:
      context: ./Auth-Service
      dockerfile: dockerfile.prod
    env_file:
      - .env
      - ./Auth-Service/.env.compose
    volumes:
      - ./Auth-Service:/app
      - ./Auth-Service/package.json:/app/package.json
    restart: always

  kiosk-service:
    build:
      context: ./Kiosk-Service
      dockerfile: dockerfile.prod
    env_file:
      - .env
      - ./Kiosk-Service/.env.compose
    volumes:
      - ./Kiosk-Service:/app
      - ./Kiosk-Service/package.json:/app/package.json
    restart: always

  app-mobile-service:
    build:
      context: ./App-Mobile-Service
      dockerfile: dockerfile.prod
    env_file:
      - .env
      - ./App-Mobile-Service/.env.compose
    volumes:
      - ./App-Mobile-Service:/app
      - ./App-Mobile-Service/package.json:/app/package.json
    restart: always
  
  records-service:
    build:
      context: ./Records-Service
      dockerfile: dockerfile.prod
    env_file:
      - .env
      - ./Records-Service/.env.compose
    volumes:
      - ./Records-Service:/app
      - ./Records-Service/package.json:/app/package.json
    restart: always

  loans-service:
    build:
      context: ./Loans-Service
      dockerfile: dockerfile.prod
    env_file:
      - .env
      - ./Loans-Service/.env.compose
    volumes:
      - ./Loans-Service:/app
      - ./Loans-Service/package.json:/app/package.json
    restart: always
    
  contributions-service:
    build:
      context: ./Contributions-Service
      dockerfile: dockerfile.prod
    env_file:
      - .env
      - ./Contributions-Service/.env.compose
    volumes:
      - ./Contributions-Service:/app
      - ./Contributions-Service/package.json:/app/package.json
    restart: always