services:

  nats-server-dev:
    build: ./Gateway-Service/nats
    ports:
      - 8222:8222
      - 4222:4222
    restart: always

  gateway-service-dev:
    build: ./Gateway-Service
    env_file:
      - .env
      - ./Gateway-Service/.env.compose
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./Gateway-Service/src:/usr/src/app/src
      - ./Gateway-Service/package.json:/usr/src/app/package.json
    command: yarn start:dev
    restart: always

  beneficiary-service-dev:
    build: ./Beneficiary-Service
    env_file:
      - .env
      - ./Beneficiary-Service/.env.compose
    volumes:
      - ./Beneficiary-Service/src:/usr/src/app/src
      - ./Beneficiary-Service/package.json:/usr/src/app/package.json
    command: yarn start:dev
    restart: always

  global-service-dev:
    build: ./Global-Service
    env_file:
      - .env
      - ./Global-Service/.env.compose
    volumes:
      - ./Global-Service/src:/usr/src/app/src
      - ./Global-Service/package.json:/usr/src/app/package.json
    command: yarn start:dev
    restart: always

  auth-service-dev:
    build: ./Auth-Service
    env_file:
      - .env
      - ./Auth-Service/.env.compose
    volumes:
      - ./Auth-Service/src:/usr/src/app/src
      - ./Auth-Service/package.json:/usr/src/app/package.json
    command: yarn start:dev
    restart: always

  kiosk-service-dev:
    build: ./Kiosk-Service
    env_file:
      - .env
      - ./Kiosk-Service/.env.compose
    volumes:
      - ./Kiosk-Service/src:/usr/src/app/src
      - ./Kiosk-Service/package.json:/usr/src/app/package.json
    command: yarn start:dev
    restart: always